In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("New_Dataset/NCG_sentences.csv")

In [3]:
!mkdir submission

In [4]:
cd submission

/home/ammaar/Desktop/TaskA/submission

In [5]:
#df = df[df['labels'] == 1]

In [6]:
df

,topic,paper_ID,text,main_heading,sub_heading,pos1,pos2,pos3,ofs1,ofs2,ofs3,length
0,constituency_parsing,0,Recurrent Neural Network Grammars,title,title,2,1,1,0.008969,1.000000,1.000000,4
1,constituency_parsing,0,"In this paper , we introduce recurrent neural ...",introduction,introduction,12,5,5,0.053812,0.238095,0.238095,29
2,constituency_parsing,0,RNNGs operate via a recursive syntactic proces...,introduction,introduction,13,6,6,0.058296,0.285714,0.285714,35
3,constituency_parsing,0,The foundation of this work is a top - down va...,introduction,introduction,14,7,7,0.062780,0.333333,0.333333,16
4,constituency_parsing,0,"We give two variants of the algorithm , one fo...",introduction,introduction,15,8,8,0.067265,0.380952,0.380952,24
...,...,...,...,...,...,...,...,...,...,...,...,...
3201,natural_language_inference,9,We then further finetuned the model on the tra...,experiment,Experiments,55,3,3,0.846154,0.300000,0.300000,17
3202,natural_language_inference,9,We trained the model by minimizing loss L from...,experiment,Experiments,56,4,4,0.861538,0.400000,0.400000,26
3203,natural_language_inference,9,Evaluation completed in about 5 hours on the N...,experiment,Experiments,58,6,6,0.892308,0.600000,0.600000,20
3204,natural_language_inference,9,Our BERT model for NQ performs dramatically be...,experiment,Experiments,60,8,8,0.923077,0.800000,0.800000,18
3205,natural_language_inference,9,Our model closes the gap between the F 1 score...,experiment,Experiments,61,9,9,0.938462,0.900000,0.900000,40

In [7]:
series = df.groupby(['topic', 'paper_ID']).size().reset_index().rename(columns={0:'count'})

In [8]:
series[0:15]

                     topic  paper_ID  count
0     constituency_parsing         0     13
1     constituency_parsing         1     16
2     constituency_parsing         2      9
3     constituency_parsing         3     21
4     constituency_parsing         4      9
5     constituency_parsing         5     15
6     constituency_parsing         6      8
7     constituency_parsing         7      7
8     constituency_parsing         8     14
9   coreference_resolution         0     15
10  coreference_resolution         1     20
11  coreference_resolution         2      8
12  coreference_resolution         3     16
13  coreference_resolution         4     32
14  coreference_resolution         5     22

In [9]:
task = ""

In [10]:
topics = series['topic'].to_list()
papers = series['paper_ID'].to_list()

In [11]:
l = len(topics)
for i in range(l):
    topic = topics[i]
    num = papers[i]
    if(topic == task):
        !mkdir $num
    else:
        if(task != ""):
            os.chdir("..")
        task = topic
        !mkdir $topic
        os.chdir(topic)
        !mkdir $num

In [12]:
series[150:155]

                          topic  paper_ID  count
150  natural_language_inference        27     22
151  natural_language_inference        28     28
152  natural_language_inference        29     14
153  natural_language_inference        30     26
154  natural_language_inference        31     23

In [13]:
!pwd

/home/ammaar/Desktop/TaskA/submission/natural_language_inference

In [14]:
os.chdir("..")

In [15]:
topics = df['topic'].to_list()
papers = df['paper_ID'].to_list()
sent = df['pos1'].to_list()

In [16]:
task = topics[0]
pid = papers[0]
l = len(topics)
sentences = []
for i in range(l):
    topic = topics[i]
    paper = papers[i]
    if(topic == task and paper == pid) or (i==0):
        sentences.append(sent[i])
    else:
        path = task + "/" + str(pid) + "/sentences.txt"
        with open(path, mode='wt', encoding='utf-8') as file:
            for x in sentences:
                file.write("%i\n" % x)
        task = topic
        pid = paper
        sentences = [sent[i]]

In [17]:
pid

9

In [18]:
path = task + "/" + str(pid) + "/sentences.txt"
with open(path, mode='wt', encoding='utf-8') as file:
    for x in sentences:
        file.write("%i\n" % x)

In [19]:
l = len(topics)
for i in range(l):
    topic = topics[i]
    paper = papers[i]
    path = topic + "/" + str(paper)
    filepath = os.path.join(path, 'entities.txt')
    f = open(filepath, "w")
    f.close()
    dir_path = os.path.join(path, 'triples')
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)